# Generated by Django 4.2.1 on 2024-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
