# Generated by Django 4.2.1 on 2024-05-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_amount_alter_bid_bidder_alter_bid_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
